version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.13.1
    container_name: portainer
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000
    restart: always
    labels:
      - owner=acme

volumes:
  data: